config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'posts/show', to: "posts#show"

  get 'posts', to: 'posts#index'

  get 'posts/new', to: 'posts#create'

  post 'posts/new', to: 'posts#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@latest_post = Post.last
		render 'pages/index'
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all.limit(10)
		render 'posts/index'
	end

	def show
		render 'posts/show'
	end

	def create
		@post = Post.new()
		render 'posts/create'
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<h3>Test footer</h3>

</body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to My Refresher Blog</h1>
<h4><%= @latest_post.title %></h4><span><%= @latest_post.created_at %></span>
<p><%= @latest_post.content %></p>
<%= link_to "Posts", posts_path %>

app/views/posts/create.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :content %>:
  <%= f.text_field :content %><br />

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h2>Posts Page</h2>
<%= link_to "Create", "posts/new" %> 

<% @posts.each do |post| %>
	<h4><%= post.title %><h4><span><%= post.created_at %></span>
	<p>Post: <%= post.content %></p>
	<% if post.comments != nil %>
		<% post.comments.each do |comment| %>
			<p style="color: grey;">     Comment: <%= comment.content %></p><span><%= comment.created_at %></span>
		<% end %>
	<% end %>
	<hr>
<% end %>